- app/components/receive-menu.js
- app/components/toggle-receive-menu-list.js
- app/templates/components/receive-item.hbs
- app/templates/components/receive_menu.hbs
- circle.yml
- tests/acceptance/receive-tab-close-options-test.js
Hi Team,
This PR is for ticket  https://jira.crossroads.org.hk/browse/GCW-1798.
It contains following changes:
- Only keeps one item option at a time
- Item option can be closed by clicking on any  
- Same feature as implemented in Stock App https://jira.crossroads.org.hk/browse/GCW-1775
- Test cases added
- Increases code-coverage by 1.1%
Thanks.
> GCW 1798 close on click for admin app

- .circleci/config.yml
- Rakefile
- cordova/config.xml
Hi Team,
This PR fixes issue of iOS build for new push plugin version.
- It installs `1.9.2` v of `phonegap-plugin-push` for iOS
- `2.1.2` for Android
Last working iOS build of branch:- https://circleci.com/gh/crossroads/admin.goodcity/4742
Last working Android build of branch:- https://circleci.com/gh/crossroads/admin.goodcity/4744
Please review it and let me know if any changes are required.
Thanks
> Phonegap push plugin fix

- cordova/config.xml
Hi Team,
This PR is for iTunes rejection of iOS due to Missing Purpose String in Info.plist File. https://jira.crossroads.org.hk/browse/GCW-2260. I have added the fix.
Please review the PR and let me know if any change is required.
Thanks
> GCW-2660- iTunes rejection fix

- package.json
- yarn.lock
Hi Team,
I have fixed vulnerabilities for:
- minimatch
- extend
- npm
- deep-extend
- hoek
- lodash
I have not fixed vulnerability for cryptiles as it requires node upgrade and parse-json do not have patched version.
Please review.
Thanks.
> Resolve vulnerabilities

- app/components/package-select-list.js
Hi Team,
This PR fixes issue related to changing of component's `PackageType` and `Notes` on going back and forth in item's accept page. It was because we were applying `notes` and `packageType` of Item's `packageType` instead of `package` itself.  
`const packageType = this.get("pkg.packageType") || this.get("pkg.item.packageType");` .
This change will also fix issue mentioned in ticket GCW-2228 and GCW-2493.
Please review the PR and let me know if any change is required.
Thanks
> GCW-2482- Changing the item type for components isn't working

- app/controllers/receive_package.js
- app/templates/receive_package.hbs
- tests/acceptance/receive_package_test.js
Hi Team,
This PR has fix for resetting of receive package form on printing Inventory number. It was because all fields of Package were grouped inside single computed property (packageForm). On calling print_barcode, the inventory_number is updated which calls the packageForm computed property and it resets all fields. I separated inventory_number field from packageForm.
I refactored `getters` and `setters` of form element also refactored code related to validation.
Please review this PR.
Thanks.
> GCW-2559 print inventory cleans form data

- app/controllers/users.js
The `my_list` page has been deleted and replaced by the dashboard. But this navigation was still trying to open the old page (causing an error popup)
> Fix: user search navigating to deleted page

- app/helpers/offers-count-display.js
Hi Team,
This PR is fix for issue on dashboard for showing same count for both priority and non-priority states. Earlier logic ignores `priority_states` offers which in turn displays`non-priority` states offers. 
Please review this PR.
> GCW-2766-Dashboard Offers count remains same for both priority and non-priority.

- app/styles/templates/offer/_search_company.scss
Hi Team,
This PR fixes issue: `create new user` and `create new company` links are not clickable on the iPhone.
Please review.
Thanks.
> fix: new user and new company links not clickable on iphone

- app/styles/templates/review_offer/_donor_details.scss
Hi Team,
This PR fixes add new contact and add new company links are not clickable on iphone.
Please review.
Thanks.
> fix add contact and add company links are not clickable on iphone

- app/controllers/users.js
- app/styles/templates/_search.scss
Hi team,
**Ticket link**
https://jira.crossroads.org.hk/browse/GCW-2795
**What does this PR do ?**
Bug:  This PR solves the issue of 
1. (If the close icon is selected, no further search results will appear if anything else is inputted into the search bar (until the page is refreshed)). 
2. Close icon glich on internet explorer 11 and edage.
**Impacted Areas**
Admin app users search widget.
Thanks
> Gcw 2795 fix search bar ui issue on users page

- app/styles/templates/_review_item.scss
Hi Team,
**Ticket Link**
https://jira.crossroads.org.hk/browse/GCW-2796.
**Bug**
This PR contains addition of vender prefixes to the transform property applied to search widget so that it also supports on the Internet explorer and other browsers.
**Screenshot**
**Impacted Areas** 
Admin app /Search-label page search widget.
> GCW-2796 Search widget on /Search-label page is right aligned.

- app/controllers/receive_package.js
- app/routes/receive_package.js
https://jira.crossroads.org.hk/browse/GCW-2831
BUG: This PR rollback changes from `package` objects after receiving error from api. And removed `PUT` request on leaving the page.
"Receive Package" page . On leaving the receive package page by pressing "Cancel" button will not receive package.
> GCW-2831- Assigning assigned inventory number while receiving package receives package without inventory number

- config/environment.js
BUG: When a rollbar error was being sent, the application environment was not being correctly determined. This fixes that and removes repetitive config that set to the default.
> App environment was not being correctly sent to Rollbar.

- app/styles/templates/donors/new.scss
https://jira.crossroads.org.hk/browse/GCW-2949
NOTE: Specify ticket link
Bug:
This PR adds background color to the select box option and removes the unwanted padding added to the select box.
Please review
> GCW-2949 removed unwanted padding and set color to option

- app/styles/templates/donors/new.scss
https://jira.crossroads.org.hk/browse/GCW-2949
Bug:
This PR adds background color to the select box option and removes the unwanted padding added to the select box.
Please review
> GCW-2849 fix for internet explorer ui issue for select box

- cordova/scripts/delete_arch.sh
This PR is for changing the path of plugins folder for removing incompatible architecture from `TwilioVoice.Framework` file. Destination changed from `S.Admin GoodCity` to `Admin GoodCity`.
Please review this PR.
> FIX=> iOS build failure for live

- app/components/receive-menu.js
- app/templates/components/receive_menu.hbs
https://jira.crossroads.org.hk/browse/GCW-2182
BUG: For closed offer, on receive tab of the package `disabled` links also shows pop-up modal when clicked.
NOTE: Added check for whether the event is already applied. Passing same value of `disabled` attribute in action, which will avoid action to be performed when link is disabled. 
Offer receive tab
> GCW-2182 fixed action on disabled menus at receive tab

- cordova/config.xml
Hi Team,
This PR fixes iOS app not working on 13.1+ version. As issue posted by Tim that app is not working on iPad 7th generation device.
I tested it on emulator with the upgraded version its working in fine.
Please review this PR.
> FIX=> iOS app not working on iOS 13.1+ version

- app/components/receive-menu.js
- app/controllers/offer/search_label.js
- app/controllers/receive_package.js
- app/controllers/review_item/accept.js
- app/mixins/async_tasks.js
- app/models/package.js
- app/services/package-service.js
- app/templates/components/receive-item.hbs
- app/templates/review_item/accept.hbs
- tests/acceptance/accept-test.js
- tests/acceptance/receive_package_test.js
- tests/factories/package.js
- tests/unit/models/package-test.js
This PR is dependant on https://github.com/crossroads/api.goodcity/pull/926
- The admin app now **only** reads/writes the `received_quantity` field, which will be used by the API to **inventorize** the package (when location and inventory_number are set)
- Marking a package as missing is now done via the `/package/1/mark_missing` endpoint, which will **uninventorize** the package
Roadmap: We will eventually want the `inventory` action to be through its own entry point. But for now, to ensure backwards compatibility, we'll let that happen in the default `PUT update`
> Mark missing via endpoint + Quantity field change

- .circleci/config.yml
- app/controllers/image_editor.js
- app/controllers/receive_package.js
- app/mixins/async_tasks.js
- app/models/package.js
- app/router.js
- app/routes/package/image_editor.js
- app/services/api-base-service.js
- app/services/image-service.js
- app/styles/app.scss
- app/styles/templates/_image_editor.scss
- app/templates/image_editor.hbs
- app/templates/receive_package.hbs
- app/utils/utility-methods.js
- yarn.lock
**Original issue:**
The `edit_images` page from the "Inventory form" would modify the Item, and not the Package.
After looking into it, I found this `edit_images` page not to be generic at all. References to the item are hardcoded everywhere. Sadly, since it is shared with the donor app, refactoring it is very risky.
**Fix:**
I copied this page into admin, as `image_editor` and transformed it to be completely generic. It can accept any kind of Imageable record, and will simply allow us to update its images.
**Note 1**
The way pages are shared between donor and admin app is _dangerous_. It's messy, un-reusable and we need to move away from this. I'm in support any actions you take toward this goal :)
If anyone has trouble understanding why, feel free to ping me with questions.
**Note2** …
> Inventory image editor fix

- .circleci/config.yml
- Rakefile
- fastlane/Fastfile
https://jira.crossroads.org.hk/browse/GCW-3304
FEATURE: Deprecates use of `APP_VERSION` environment variable in the app builds. Delegates to `package.json` instead.
NOTE: Previously, bumping the app version required updating `package.json` and updating `APP_VERSION` in CircleCI. This was was unnecessary duplication and made the builds less automated. After this PR is merged, version will be set entirely from code in the projects `package.json` file and we can delete `APP_VERSION` from CircleCI
- iOS App Store app version
- Google Play app version
> GCW-3303-Deprecate usage of APP_VERSION in Admin app

- app/styles/templates/components/_canned-messages-overlay.scss
- app/templates/components/canned-content.hbs
https://jira.crossroads.org.hk/browse/GCW-3466
Removes the hovering over the pre-set messages to add in a message, the hand icon is used for the cursor for the part that isn't selected.
> GCW-3466 Remove the hand pointer

- app/controllers/message_base_controller.js
- app/controllers/my_notifications.js
- app/controllers/review_offer/share/index.js
- app/models/message.js
- package.json
Issue:
The admin app knows that messages are from charities when `user != donor`, that however breaks when there is no donor at all (if an admin created the offer).
> FIX: Shared chat displays are broken when there is no donor

- app/controllers/my_notifications.js
https://jira.crossroads.org.hk/browse/GCW-3487
BUG: ADMIN iOS: Error when clicking on item notification in notification tab in admin app fix
> GCW-3487-Offer_id missing in params for item notification

- app/controllers/review_offer.js
- app/locales/en/translations.coffee
- app/locales/zh-tw/translations.coffee
- app/templates/review_offer.hbs
https://jira.crossroads.org.hk/browse/GCW-2785
Adds popup for offer deletion on clicking back button from empty offer
> GCW-2785 Add pop up for navigating from empty offer screen

- app/components/add-edit-message-overlay.js
- app/templates/components/add-edit-message-overlay.hbs
- app/templates/components/package-type-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-3532
Added `focus-out` callback for label and message and hide `Done` button on edit case.
> GCW-3532-Making Canned message Inline-edit

- app/controllers/message_base_controller.js
- app/locales/en/translations.coffee
- app/locales/zh-tw/translations.coffee
- app/templates/message_template.hbs
- yarn.lock
If a chat has no recipient (donor or charity), it is disabled to prevent staff members from sending messages to nobody (which causes side effects later down the line)
> Disable chats with no recipients

- app/controllers/receive_package.js
- app/routes/receive_package.js
Issue:
Due to the following line:
```javascript
inventoryNumber: Ember.computed.alias("package.inventoryNumber"),
```
The package's inventory number is set on the package object itself when initialized.
When the user _leaves_ the `/receive_package/:id` page without clicking "cancel" (e.g browser back button), this field isn't cleared and stays on the package locally. It later gets persisted when another page triggers `pkg.save()`
FIX:
- We only set the inventory number on the package during the PUT request to save the package. If the user exits the page beforehand, nothing gets set on the package object
> FIX: Clear inventory number state
