crossroads/admin.goodcity

app/controllers/packages.js
app/controllers/review_item.js
app/controllers/review_item/accept.js
app/styles/app.scss
app/styles/templates/_review_item.scss
app/templates/review_item.hbs
app/templates/review_item/reject.hbs
app/views/add-component-of-item.js
app/views/review_item/accept.js
tests/acceptance/accept-test.js

This PR is dependent on https://github.com/crossroads/admin.goodcity/pull/45.
Please merge https://github.com/crossroads/admin.goodcity/pull/45 before merging this PR.
Thanks.

GCW-379 Admin can set / edit donor description and item condition

---

cordova/appDetails.json
cordova/config.xml
cordova/hooks/changeAppName.sh

For production build:
TARGET=production cordova prepare <ios|android>

update cordova app-name and app-url after cordova prepare

---

app/templates/review_item/accept.hbs

Length and pattern check is added to the Package template

Added validation for the Qty, Length, width and height numeric fields

---

Rakefile
cordova/appDetails.json

donor app.Entitlement issue is there need to fix that yet

Modified build script to create a ios build for admin app

---

app/templates/my_list/reviewing.hbs
app/templates/offers/display_offer_data.hbs
app/templates/offers/submitted.hbs
package.json

- use vertical-collection component of smoke-and-mirrors to render offers list

Integrate smoke and mirrors

---

app/app.js
bower.json
config/environment.js
cordova/config.xml
package.json

Fixed ADMIN_APP_HOST_URL for development environment
Added ember-data-filter to fix the deprecation warning related to ember Filter

GCW-891 use ember-data-filter addon for filter

---

app/controllers/search_label.js
app/models/package_type.js
app/router.js
app/routes/search_label.js
app/styles/templates/_review_item.scss
app/templates/review_item.hbs
app/templates/search_label.hbs
tests/acceptance/accept-test.js
tests/acceptance/review-item-test.js
tests/acceptance/reviewer-reject-item-test.js

- basic design for assign item-type to item

Gcw 926 redesign reviewer code ui

---

app/styles/templates/review_offer/_receive.scss
app/templates/components/receive-item.hbs

Hi,
This PR modifies admin receive tab UI.
Thanks

GCW-1209 receive page ui modified for admin

---

app/routes/review_item.js

Hi Team,
This PR fixes issue mentioned on ticket GCW-1230
Thanks.

GCW-1230-add-item-values-lost-when-setting-item-type

---

Rakefile

Splunk plugin code moved to the crossroads account.

---

app/templates/components/receive_menu.hbs
bower.json
package.json
yarn.lock

- Bug fixes
- Upgrade Ember from 2.8 to 2.9

June update for 0.13.1

---

app/controllers/review_item/accept.js
app/controllers/review_item/reject.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee

Reverts crossroads/admin.goodcity#193

Revert "Gcw 1681 prevent any save operations for designated dispatched items"

---

.codeclimate.yml
Gemfile
circle.yml
package.json
yarn.lock

Added Fastlane and Credential manager gem in gemfile

Added code to support code coverage on Code climate

---

app/controllers/user.js
tests/acceptance/user-test.js

Hi,
This is pull request for jira ticket https://jira.crossroads.org.hk/browse/GCW-1870.

Gcw 1870 admin user save button previous side

---

app/styles/templates/_users.scss

Hi Team,
This PR contains changes for:
- Redirect to previous page on user save button click. (GCW-1870)
Thanks.

#MayRelease2

---

fastlane/Fastfile

Hi Team,
This PR is to remove fastlane deprecation warning. Please review and let me know in case of any changes.
Thanks.

Remove fastlane deprecation warning

---

app/locales/zh-tw/translations.coffee

Hi Team,
This PR is for adding chinese translations.
https://jira.crossroads.org.hk/browse/GCW-2112
Please review.
Thanks.

added missing chinese translation for QuotaExceededError

---

app/controllers/review_offer.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee

Hi Team,
This is PR for minor button text change from "Delete Offer" to "Yes".
Thanks.

GCW-2076-fixed: Text changed from Delete offer  to Yes

---

app/components/package-select-list.js
app/models/package.js
app/templates/review_item.hbs
app/templates/review_item/accept.hbs
tests/acceptance/accept-test.js
tests/acceptance/review-item-test.js

Hi Team,
This is PR for Jira ticket GCW-2073-Cannot save description in the accept tab
https://jira.crossroads.org.hk/browse/GCW-2073.
I have added fix for the 2 scenarios discussed in the ticket and added test cases for it.
Review the ticket and let me know if any change is required.
Thanks.

GCW-2073 Fixed issue : cannot save description in accept tab

---

.circleci/config.yml
Gemfile
Gemfile.lock
Rakefile
app/components/inventory-number-input.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
cordova/config.xml
ember-cli-build.js
fastlane/Fastfile
package.json
testem.js
yarn.lock

Hi Team,
This PR contains changes for:
- Phonegap plugin fix. (GCW-2184)
- Spelling Mistake under transport tab. (GCW-2202)
- Scanning barcode does not ask for camera permissions if they have not been granted (GCW-2203)
- Turn on fingerprinting again to deal with caching issues. (GCW-2214)
- Improve iOS build configuration for all apps. (GCW-2211)
Please Review.
Thanks.

#December2018Release1

---

config/environment.js

Hi team, this PR is for showing app versions correctly. Please review and comment.
Thanks.

GCW-2209 show app version

---

yarn.lock

Hi Team,
This PR changes commit version number to refer shared repo code.
Thanks.

Change shared repo commit version

---

app/controllers/search.js
app/templates/search.hbs
server/mocks/offers.js
tests/acceptance/search-test.js

The offers search was previously running a local search on the store. And would fetch everything from the server through the `Find more on server` button, which was a huuuuuuuge payload.
Now the search is comparable to the order search on stock, just a normal endpoint call with the search text

New offers search

---

cordova/config.xml

Contains fix for itunes issue(Fixes camera usage permission string)

March Release#2

---

yarn.lock

Upgrade staging admin to latest shared changes

upgrade shared-goodcity

---

app/components/reject-message-field.js
app/controllers/review_item/reject.js
app/routes/review_item/reject.js
app/templates/review_item/reject.hbs
tests/acceptance/reject-test.js

Hi Team,
This PR contains changes to save rejection reason to db on item rejection.
Changes: 
https://github.com/crossroads/admin.goodcity/pull/297/files#diff-f75890635ae234be0e4c283925c4d4e4R45
https://github.com/crossroads/admin.goodcity/pull/297/files#diff-fe9460464bf54f39387d00dae7fcd92dR12
https://github.com/crossroads/admin.goodcity/pull/297/files#diff-f81cb9b3fec5a05e75ee7c5550b6671aR126
Ticket: https://jira.crossroads.org.hk/browse/GCW-2515
Please review. 
Thanks.

GCW-2515 add 2 way binding for rejection reason

---

app/components/auto-resize-textarea.js
app/components/cancel-offer.js
app/controllers/offers.js
app/controllers/review_offer.js
app/controllers/review_offer/donor_details.js
app/controllers/review_offer/items.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/mixins/async_tasks.js
app/routes/review_offer.js
app/routes/review_offer/donor_details.js
app/styles/templates/_admin_main.scss
app/styles/templates/_review_offer.scss
app/styles/templates/review_offer/_donor_details.scss
app/templates/_review_offer_options.hbs
app/templates/app_menu_list.hbs
app/templates/components/cancel-offer.hbs
app/templates/components/inactive-offer.hbs
app/templates/offer/message_section.hbs
app/templates/offers/display_offer_data.hbs
app/templates/review_offer/donor_details.hbs
tests/acceptance/app-menu-test.js
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-2679

GCW-2679 - Allow staff to create an offer

---

app/styles/templates/_search.scss
app/templates/search.hbs

Hi Team,
This PR is for scroll issue on search filter UI. Please review the PR and let me know if any change is required. 
Thanks

FIX=> Search filter scroll issue

---

app/styles/templates/_search.scss

Hi Team,
This PR is for removing horizontal scrollbar on Offer search page. Please review the PR and let me know if any change is required.

FIX=> Horizontal scrollbar on search page

---

config/environment.js

Hi Team,
This PR migrates GCM to FCM.
Please review.
Thanks.

migrate gcm to fcm

---

app/routes/dashboard/index.js
app/templates/dashboard.hbs

@abulsayyad123 I don't think you did anything wrong, but the app is weirdly structured. The menu list seems to be "injected" into each page, which is odd.
I think the expectation is to have pages embedded into an application template which has the sidebar, which is why you wouldn't expect to have to do this
I copied everything from the '/offers' pages to make it work

Fix sidebar on branch GCW-2685

---

app/controllers/receive_package.js

Hi Team,
This PR is for quality field is getting reset on printing inventory number. Please review this PR.

FIX=> quality field getting reset on inventory number print

---

app/controllers/review_offer/items.js
app/templates/offer/message_section.hbs
tests/acceptance/reviewer-offer-tab-test.js
yarn.lock

Disabled add item button when offer is finished

---

app/index.html
app/styles/app.scss
app/styles/global_styles.scss
app/styles/templates/_dashboard.scss
app/templates/dashboard/_active_offers.hbs
app/templates/dashboard/_inactive_offers.hbs
app/templates/dashboard/_recent_new_offers.hbs

Hi Team,
This ticket is for minor UI fixes for Offer search filter UI and Admin Dashboard fixes.

FIX=> UI fixes for Offers Filter and Dashboard

---

app/styles/templates/_dashboard.scss

Fix for this https://crossroads-hk.slack.com/archives/GBJAFNVFB/p1565334785208700
Please review. 
Thanks

Fix css for dashboard

---

app/styles/templates/_dashboard.scss
app/templates/dashboard/_inactive_offers.hbs
package.json
yarn.lock

Fixes this issue, minor typo
https://crossroads-hk.slack.com/archives/GBJAFNVFB/p1565587109223400

fix inactive tab taking to received offer_filter selection

---

.circleci/config.yml
app/controllers/my_notifications.js
app/controllers/notification_link.js
app/controllers/review_offer.js
app/controllers/users.js
app/routes/my_notifications.js
app/templates/my_notifications.hbs
app/templates/notification_link.hbs
app/templates/users.hbs
package.json
tests/acceptance/app-menu-test.js
tests/acceptance/edit-images-test.js
tests/acceptance/logistic-tab-test.js
tests/acceptance/my-notifications-test.js
tests/acceptance/review-item-test.js
tests/acceptance/search-test.js
tests/acceptance/user-test.js
yarn.lock

Hi here are the changes from this PR:
- Removal of the offers preload (in shared.goodcity)
- Removal of the complete preload of messages, instead the notification page is now paginated with the infinite list module
- Users search is done on the backend
Note: Some tests have been commented because they are pretty darn hard to fix, and we need this out sooner than later. I'll retroactively resolve them.
I foresee some small bugs given that it's a pretty big change, so some testing will be needed

Paginated notifications + Remote user search

---

app/controllers/donors/new.js
app/routes/donors/new.js

Hi Team,
It reset new donor form. Previously it was showing old values whenever we used to come back to the form.
Please review.
Thanks.

reset donor form

---

app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/styles/templates/donors/new.scss
app/styles/templates/review_offer/_donor_details.scss
app/templates/companies/new.hbs
app/templates/donors/new.hbs
app/templates/review_offer/donor_details.hbs
yarn.lock

Minor fixes:
- remove validation from crm-id
- Add cancel button on new donor screen
- Display correct mobile number on donor_details screen
- Increase the size of icons on donor_details page for small screens so that it easy to click through mobile as well

GCW-2691 fix minor issues in corporate donor

---

app/styles/templates/_offers.scss
app/templates/_offer_title.hbs
app/templates/offers/display_offer_data.hbs
app/templates/review_offer.hbs

Hi Team,
This PR is for including company name &/or title on Offers title. Please review this PR and let me know if any change is required.

GCW- 2695- include company name &/or note in offer title and search

---

yarn.lock

Upgrade yarn to latest shared.

upgrade yarn

---

app/controllers/receive_package.js
app/controllers/search_label.js
app/templates/receive_package.hbs
app/templates/review_offer/receive.hbs

Hi Team,
This PR has fix for displaying 'Add unplanned item' for receiving state, removing zero prefix on label count on print button and also restricting dimensions value to 3 digit.

FIX=> Showing 'Add unplanned Item' on receiving state.

---

yarn.lock

Hi Team,
This PR contains the latest commit hash of shared repo.
Please review.
Thanks.

update shared version in yarn lock

---

app/styles/templates/_search.scss
app/styles/templates/_users.scss
app/templates/users.hbs

Hi Team,
https://jira.crossroads.org.hk/browse/GCW-2795
This PR contains the fixing the UI of search widget on /users page. 
Fixed UI Screen shot:
Thanks.

Gcw 2795 fix search bar ui issue on users page

---

app/controllers/offer/search_label.js
app/controllers/receive_package.js
app/controllers/search_label.js
app/router.js
app/routes/offer/search_label.js
app/routes/receive_package.js
app/templates/review_offer/receive.hbs
app/templates/search_label.hbs
tests/acceptance/receive_package_test.js

Hi Team,
This PR is for fixing item and package deletion on using browser back button. Removed Item creation on redirecting to `search_label` and removed dependency of deleting Item on redirecting back. Also, handled deletion of Items and package on using browser back button.
Please review the PR and let me know if any change is required.

FIX=> Print Inventory back issue

---

app/controllers/companies/edit.js
app/templates/_offer_title.hbs
app/templates/companies/edit.hbs
app/templates/review_offer/donor_details.hbs
yarn.lock

This PR uses the computed property `companyName` created in `offer.js` on shared for displaying the correct companyName.
Please review
Thanks

Fix edit company errors

---

.circleci/config.yml

https://jira.crossroads.org.hk/browse/GCW-2809
It adds new p12 and provisioning profiles for production.
Please Review.
Thanks.

Gcw 2809 renew ios certificates

---

app/controllers/review_item/accept.js
app/controllers/search_label.js
app/routes/review_item/accept.js
tests/acceptance/review-item-test.js
tests/factories/package_type.js

https://jira.crossroads.org.hk/browse/GCW-2642
BUG: This PR fixes the selection of sub package types based on the selection of package type.
Changes Links:
https://github.com/crossroads/admin.goodcity/pull/362/files#diff-ccb2ab2d72fb2ce154ba65513ab7d553R55
https://github.com/crossroads/admin.goodcity/pull/362/files#diff-ccb2ab2d72fb2ce154ba65513ab7d553R98
https://github.com/crossroads/admin.goodcity/pull/362/files#diff-ccb2ab2d72fb2ce154ba65513ab7d553R116
https://github.com/crossroads/admin.goodcity/pull/362/files#diff-03a7a9420bc3395dbff78448469cbb14R113
https://github.com/crossroads/admin.goodcity/pull/362/files#diff-d4231bbde05666d6e2a3a9b8b87034c3R7
Please review.
Thanks

Gcw 2642 sub packages are not correctly setup

---

app/controllers/receive_package.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/models/location.js
app/models/printer.js
app/routes/receive_package.js
app/services/printer-service.js
app/styles/app.scss
app/styles/templates/_receive_package.scss
app/templates/receive_package.hbs
config/environment.js
package.json
server/mocks/printers.js
server/mocks/users.js
tests/acceptance/accept-test.js
tests/acceptance/receive_package_test.js
tests/factories/printer.js
tests/factories/user.js
tests/factories/user_profile.js
tests/factories/user_role.js
tests/unit/models/offer-test.js
tests/unit/models/printer-test.js
yarn.lock

Ticket Link:
https://jira.crossroads.org.hk/browse/GCW-2853
What does this PR do?
FEATURE: Add a "Printer" single select control at the bottom right of the create form (in both admin and stock apps)
Please review
Thanks.

printer dropdown UI for admin ready

---

app/services/printer-service.js
app/styles/templates/_receive_package.scss
app/templates/receive_package.hbs

Ticket Link:
https://jira.crossroads.org.hk/browse/GCW-2853
This PR contains sorting the printer option in UI by id and CSS and ui fixes

GCW-2853 added sort by for printer option and css fixes

---

.circleci/config.yml
app/controllers/receive_package.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/models/location.js
app/models/printer.js
app/routes/receive_package.js
app/services/printer-service.js
app/styles/app.scss
app/styles/templates/_receive_package.scss
app/templates/receive_package.hbs
config/environment.js
package.json
server/mocks/printers.js
server/mocks/users.js
tests/acceptance/accept-test.js
tests/acceptance/receive_package_test.js
tests/factories/printer.js
tests/factories/user.js
tests/factories/user_profile.js
tests/factories/user_role.js
tests/unit/models/offer-test.js
tests/unit/models/printer-test.js
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-2853
FEATURE: This ticket provides a UI for end users to select a printer and to set their own default printer when creating new packages
Please review
Thanks

Gcw 2853 support printer selection in ui feature live

---

Gemfile.lock

Hi Team,
This PR upgrades Fastlane version. Please review.
Thanks.

upgrade fastlane version

---

app/styles/templates/_dashboard.scss

NOTE: Specify ticket link
https://jira.crossroads.org.hk/browse/GCW-2934.
Bug:
This PR fixes the alignment issue present on Dashboard page for 320 width devices.
Thanks.

GCW-2934 Admin dashboard aligenment issue solveds

---

.circleci/config.yml
config/deploy.rb
config/deploy/preview.rb
config/environment.js
ember-cli-build.js
package.json
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-2905
FEATURE: Adds a preview environment alongside staging and production.
Removes the `STAGING=true` environment build variable and replaces it with `ENVIRONMENT=(staging|preview|production)`
Previously we would write
```
EMBER_CLI_CORDOVA=0 STAGING=true yarn run ember build --environment=production
EMBER_CLI_CORDOVA=0 STAGING=false yarn run ember build --environment=production
yarn run ember build --environment=development
yarn run ember build --environment=test
```
Now we write
```
EMBER_CLI_CORDOVA=0 ENVIRONMENT=staging yarn run ember build --environment=production
EMBER_CLI_CORDOVA=0 ENVIRONMENT=preview yarn run ember build --environment=production
EMBER_CLI_CORDOVA=0 ENVIRONMENT=production yarn run ember build --environment=production
yarn …
```

Added new preview build environment.

---

package.json

Bump package.json version and resolve merge conflicts

Resolving conflicts live master

---

app/config/offer-sorting-options.js
app/controllers/companies/new.js
app/templates/companies/new.hbs

Hi All,
This PR fixing the sort by names and added action to add company save button.
Please review.

GCW-2906 used correct name for sorting and added action on save form

---

app/templates/components/offer-filters-button.hbs
app/templates/search.hbs

https://jira.crossroads.org.hk/browse/GCW-2947
Bug: This PR fixes the horizontal scroll issue present on search page admin app
Please review.

GCW-2947 horizontal scroll issue resolved

---

.circleci/config.yml
app/styles/templates/_search.scss
app/templates/search.hbs

https://jira.crossroads.org.hk/browse/GCW-2947
This PR contains decreasing the size of input fields on small device.
Please review.

Gcw 2947 horizontal scroll input field issue

---

app/templates/search.hbs

https://jira.crossroads.org.hk/browse/GCW-2947
Bugs: removed unwanted row class div from the search field.
Please review.

GCW-2947 removed unwanted div

---

package.json

Bump app version
Please review this PR

Bump app version

---

yarn.lock

Upgrade the admin app to the latest shared-goodcity

upgrade admin app to latest shared

---

app/components/date-picker.js
app/components/offer-filters.js
app/templates/_time_filters.hbs

jira.crossroads.org.hk/browse/GCW-2744
Adds the date limit based on the "on or before" and "after" date filters for the due dates
Admin App -> Filter by due
-NA-
-NA-
NOTE: If these changes are related to some existing PR or fixes any issue from existing PR changes, specify PR links.
-NA-

GCW-2744 Fix impossible search criteria with the 'On or after' and 'On or before' filters

---

app/components/date-picker.js

https://jira.crossroads.org.hk/browse/GCW-2744
Fixes the mobile issue for date filter mentioned by Tim

GCW-2744 fix for mobile date filter issue

---

app/controllers/review_item.js
app/templates/review_item.hbs

https://jira.crossroads.org.hk/browse/GCW-2644
Additional support as in the comment
https://jira.crossroads.org.hk/browse/GCW-2644?focusedCommentId=38052&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-38052

GCW-2644 Show copy icon only for items which are not in draft state

---

tests/acceptance/review-item-test.js
tests/acceptance/selecting-package-type-test.js

Some specs failing (exclusively) on master.
I'll fast track this to Staging to fix the build. Please review retrospectively

Fix master build

---

yarn.lock

Added changes to yarn.lock

---

yarn.lock

Upgrade recent yarn.lock file

---

app/controllers/review_item.js

https://jira.crossroads.org.hk/browse/GCW-2644
Fixes the issue reported by Tim while testing

GCW-2644 Fix image copy not showing till page refresh

---

yarn.lock

Upgraded yarn file

---

yarn.lock

Uppdated yarn.lock

---

tests/factories/donor_condition.js

FIX=> failing mixed condition test cases

---

tests/acceptance/accept-test.js
tests/factories/donor_condition.js

Fix => Donor condition failing specs

---

bower.json
ember-cli-build.js
fastlane/Fastfile

- Fastfile change to make sure errors stop the build process
- GCW-3172 - Image metadata error

FIX: fastlane + image upload bug

---

app/services/printer-service.js

https://jira.crossroads.org.hk/browse/GCW-3238
List printers in alphabetical order in drop-down. Added its change in printer-service.

GCW-3238- List printers in alphabetical order

---

app/controllers/my_notifications.js
app/routes/my_notifications.js
app/styles/templates/_my_notifications.scss
app/styles/templates/_offers.scss
app/templates/my_notifications.hbs
tests/acceptance/my-notifications-test.js
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-3200
Include item message notifications on alerts page

GCW-3200 Include item message notifications on alerts page

---

app/controllers/receive_package.js
app/models/printer.js
app/models/printers_user.js
app/routes/receive_package.js
app/services/printer-service.js
app/utils/helpers.js
tests/acceptance/receive_package_test.js
tests/factories/printers_user.js
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-3276
This PR adds new endpoint for updating and creating favourite printer for user in stock.

GCW-3276- Multiple favorite printers

---

.circleci/config.yml

FIX=> Web deployment step because of low bundler version #347

---

app/templates/companies/new.hbs

FIX: Action typo (saveCompanyAndOffer)

---

.circleci/config.yml
app/controllers/review_offer.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/services/offer-service.js
app/templates/_review_offer_options.hbs
package.json
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-3285
FEATURE: This PR adds feature to reopen closed/cancelled offers.

GCW-3285- Add a 'reopen' button to the offer details page

---

app/components/cancel-offer.js
app/components/inactive-offer.js
app/templates/components/cancel-offer.hbs

https://jira.crossroads.org.hk/browse/GCW-3325
BUG: When cancelling an order, there are two 'Other' options fix

GCW-3325-When cancelling an order, there are two 'Other' options fix

---

app/components/receive-menu.js
app/controllers/receive_package.js
app/services/printer-service.js

https://jira.crossroads.org.hk/browse/GCW-3301
This PR sends `tag` params for printing the favourite of the user.

GCW-3301- Selecting default printer while doing `print_label` command.

---

app/index.html
cordova/config.xml

https://jira.crossroads.org.hk/browse/GCW-3375
`window.platform.device` was not getting recognized because of obsolete plugins. Upgrading plugins fixed this issue.

GCW-3375-The Admin app comes up with a popup message and it's also not possible to search for orders.

---

app/controllers/review_offer.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/services/offer-service.js
app/styles/templates/_admin_main.scss
app/templates/_review_offer_options.hbs
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-3285
This PR adds "resume_receiving" action to transition offer from Received to Receiving state.

GCW-3285- transition offer from Received to Receiving

---

app/controllers/companies/edit.js
app/controllers/companies/new.js
app/styles/templates/companies/new.scss
app/templates/_offer_title.hbs
app/templates/companies/edit.hbs
app/templates/companies/new.hbs
app/templates/review_offer/donor_details.hbs

https://jira.crossroads.org.hk/browse/GCW-3395
FEATURE:  Adding a company to an order after attempting to create a company with a blank name does not display the company fix.

GCW-3395-Adding a company to an order after attempting to create a company with a blank name does not display the company fix

---

app/controllers/companies/edit.js
app/controllers/companies/new.js
app/templates/companies/new.hbs

https://jira.crossroads.org.hk/browse/GCW-3395?focusedCommentId=42176&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-42176
BUG:QA Fix for  Adding a company to an order after attempting to create a company with a blank name does not display the company.

GCW-QA fixes for adding company to offers

---

Gemfile.lock
app/templates/dashboard/_recent_new_offers.hbs

https://jira.crossroads.org.hk/browse/GCW-3399
FEATURE: Specify feature name

GCW-3399 Adding New Offers count in dashboard

---

app/components/canned-content.js
app/styles/templates/components/_canned-messages-overlay.scss
app/templates/components/canned-content.hbs
app/templates/components/canned-messages-overlay.hbs

- Adds ability to expand canned message on click
- Fix issue of clear search icon being cut out of search box

GCW-3389 Add ability to expand canned message on click

---

Gemfile.lock
app/controllers/companies/edit.js
app/controllers/companies/new.js
app/styles/templates/components/_canned-messages-overlay.scss
app/templates/companies/edit.hbs
app/templates/companies/new.hbs
app/templates/dashboard/_recent_new_offers.hbs
yarn.lock

**Generated on:** 12/21/2020, 12:58:32 PM
**Repository:** `https://github.com/crossroads/admin.goodcity.git`
- [GCW-3428](https://jira.crossroads.org.hk/browse/GCW-3428) Admin: The 'x' button for the canned messages search is difficult to select on iOS
- [GCW-3394](https://jira.crossroads.org.hk/browse/GCW-3394) Admin: I was able to create a new company without entering anything into the 'Company Name' field on the 'Create New Company' page.

[Release] Admin v0.17.7

---

package.json

Bumps Version

---

app/controllers/receive_package.js
app/models/package.js
app/routes/receive_package.js
app/services/package-service.js
app/templates/receive_package.hbs
package.json
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-3440
Fix inventorying items via the admin app, the "value" field is not being set

GCW-3440 Fix inventoried items having $0 always

---

app/controllers/review_offer/share/index.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/styles/templates/review_offer/_share.scss
app/templates/review_offer/share/_editor.hbs
config/environment.js

Changes:
- Browse dev url was wrong
- Sharing editor was not scrollable
- Select all feature was not implemented

GCW-3465  FIX: Scrolling on sharing editor + select all feature

---

app/controllers/review_item/accept.js

https://jira.crossroads.org.hk/browse/GCW-3334
BUG: Item condition not saved when description is also edited fix

GCW-3334 Item condition not saved when description is also edited fix

---

app/components/receive-menu.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/routes/receive_package.js
app/templates/components/receive_menu.hbs

https://jira.crossroads.org.hk/browse/GCW-2506
This PR adds a popup for inventorying the package in the received state.

GCW-2506-Allow received item to be inventoried

---

app/controllers/receive_package.js

https://jira.crossroads.org.hk/browse/GCW-2835
GCW-2835 fixed issue with receiving packages with duplicate inventory number

GCW-2835 fixed issue with receiving packages with duplicate inventory number

---

yarn.lock

Update shared hash

---

app/components/offer-filters.js
app/controllers/search.js
app/helpers/state-filter-icon.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/services/filter-service.js
app/styles/_filters.scss
app/templates/_state_filters.hbs
tests/acceptance/search-test.js

https://jira.crossroads.org.hk/browse/GCW-3490
FEATURE: Enhancing shared offer feature

GCW 3490 enhance shared offer feature

---

app/styles/templates/_dashboard.scss

https://jira.crossroads.org.hk/browse/GCW-3511
This PR fixes the image height issue on dashboard. I tested it on all device sizes and browsers and it looks fine.

GCW-35111-fixed image height

---

app/models/canned_response.js
app/styles/templates/components/_canned-messages-overlay.scss

- Fix Delete button showing for system messages

GCW-3538 QA Fixes

---

app/components/add-holiday.js
app/components/holiday-detail.js
app/templates/components/holiday-detail.hbs

https://jira.crossroads.org.hk/browse/GCW-3570
Fix validation issue for holidays in admin goodcity

GCW-3570 Fix Validation error for holidays in admin goodcity

---

app/components/holiday-calender.js
app/components/holiday-detail.js
app/templates/components/holiday-detail.hbs

https://jira.crossroads.org.hk/browse/GCW-3570
Add validation to date field when empty date is passed on editing holiday in admin app

GCW-3570 - Resolve validation issue for date when holiday is edited in admin app

---

app/controllers/offer/merge.js
app/controllers/review_offer.js

https://jira.crossroads.org.hk/browse/GCW-2714
fixed unexpected errors at merge offer

GCW-2714 fixed unexpected errors at merge offer

---

app/routes/offer.js
app/routes/review_offer.js

https://jira.crossroads.org.hk/browse/GCW-3569
Load messages on offers and items separately.

GCW-3569 load offer and item messages seperately

---

yarn.lock

Update yarn file

---

app/controllers/review_item/accept.js
app/controllers/search_label.js
app/routes/review_item/accept.js

https://jira.crossroads.org.hk/browse/GCW-3616
Fixed issue with editing item-type at item-edit and respective updates on packages

GCW-3616 fixed updating item-type in item-edit page

---

app/routes/message_base.js
app/routes/offer/donor_messages.js
app/routes/offer/supervisor_messages.js

https://jira.crossroads.org.hk/browse/GCW-3660
When User directly visits the offer messages page or hot-reload offer messages page, it was not loading messages as messages are no longer part of offer response and hence need to be reloaded separately.

GCW-3660 Fixed General Messages Thread

---

app/controllers/my_notifications.js
app/controllers/review_offer/items.js
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-1384
fixed live-update of messages and unreadCount

GCW-1384 fixed live-update of messages and unreadCount

---

app/controllers/review_offer/share/index.js
app/helpers/user-organisation-status-icon.js
app/models/user.js
app/styles/templates/review_offer/_share.scss
app/templates/review_offer/share/index.hbs
config/environment.js

https://jira.crossroads.org.hk/browse/GCW-3662
share offer messages thread UI changes

GCW-3662 share offer messages thread UI changes

---

app/components/cancel-offer.js
app/components/complete-receive-offer.js
app/components/date-selector.js
app/components/inactive-offer.js
app/components/stop-offer-sharing.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/styles/templates/_review_offer.scss
app/styles/templates/review_offer/_receive.scss
app/templates/components/cancel-offer.hbs
app/templates/components/complete-receive-offer.hbs
app/templates/components/inactive-offer.hbs
app/templates/components/stop-offer-sharing.hbs
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-3665
Stop sharing block in offer overlay on close-offer, cancel-offer, and inactive-offer

GCW-3665 stop-sharing block on offer closure

---

app/controllers/my_notifications.js
app/controllers/review_offer/share/chat.js
app/controllers/review_offer/share/index.js
app/models/message.js
app/models/offer_response.js
app/routes/review_offer/share/chat.js
app/routes/review_offer/share/index.js
app/services/messages.js
app/templates/notification_thread.hbs

jira.crossroads.org.hk/browse/GCW-3663
FEATURE:Add offer response messages changes

GCW-3663-Add offer response table changes

---

app/components/date-selector.js
app/components/datetime-selector.js
app/components/stop-offer-sharing.js
app/controllers/review_offer/share/index.js
app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/styles/templates/_review_offer.scss
app/styles/templates/review_offer/_share.scss
app/templates/components/datetime-selector.hbs
app/templates/components/stop-offer-sharing.hbs
app/templates/review_offer/share/_editor.hbs

https://jira.crossroads.org.hk/browse/GCW-3664
Offer share page changes
mockup 
https://xd.adobe.com/view/1f58a395-6de5-4931-af94-b2dfb93519ca-4a0b/screen/e96571c3-8d2f-40b3-adce-b23d38c21b80/?x_product=xd-jiraserver%2F1.0

GCW-3664 Share offer page changes

---

app/components/datetime-selector.js
app/controllers/review_offer/share/index.js
app/models/shareable.js

Fixed code suggestions added on PR https://github.com/crossroads/admin.goodcity/pull/536#discussion_r679670001

GCW-3664 refactored datetime component

---

app/styles/templates/_offers.scss
app/templates/offers/nav_bar.hbs

https://jira.crossroads.org.hk/browse/GCW-3471

GCW-3471 fixed menu icon on dashboard page

---

config/environment.js
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-3649
FEATURE: Add timer for resending otp

Gcw 3649 add timer to otp resend pin

---

app/styles/templates/_admin_main.scss
app/templates/_review_offer_options.hbs

https://jira.crossroads.org.hk/plugins/servlet/samlsso?redirectTo=%2Fbrowse%2FGCW-3687
FEATURE: Disabling delete button for offers which are shared

GCW-3687-Disable delete offer link for shared offers

---

app/controllers/my_notifications.js
app/models/message.js
app/templates/message_template.hbs
app/templates/offer/recent_item_message.hbs
app/templates/offer/recent_offer_message.hbs
yarn.lock

Updating shared and update message model for sanitizing output

Gcw 3694 sanitizing user message input

---

app/locales/zh-tw/translations.coffee
yarn.lock

https://jira.crossroads.org.hk/browse/GCW-3720
Adds more Chinese translations to the app

Updating translations

---

app/locales/en/translations.coffee
app/locales/zh-tw/translations.coffee
app/styles/templates/_dashboard.scss
app/templates/dashboard/_recent_new_offers.hbs

https://jira.crossroads.org.hk/browse/GCW-3711
FEATURE: Admin - Provides a link to active shares from home screen

GCW-3711 Add link to active shares from home page

---

app/styles/templates/_review_item.scss
app/templates/components/package-type-overlay.hbs
app/templates/review_item.hbs

https://jira.crossroads.org.hk/browse/GCW-3706
fixed regression in category selection UI
**MOBILE SCREEN**
**DESKTOP SCREEN**
**TABLET SCREEN**

GCW-3706 fixed regression in category selection UI
